ruby_version: ruby-2.3.1
bundler_version: 1.12.2

postgresql:
  version: '9.3'

firefox: '31.0esr'

coverage:
  version: 2
  enabled: true

pipeline:
  default:
    second:
      - third
    fifth: six
    seventh:
      eight:
        nine: ten
  fourth:
    eleven:
      - twelve
      - thirteen
  fourteen: fifteen
steps:
  default:
    script: "/usr/local/repos/successful_test"
    #coverage:
    #  version: 2
    #  enabled: true
    #  ratchet: 60
    test_pattern:
      - spec/controllers/comments_controller_spec.rb
  second:
    script: "/usr/local/repos/successful_test"
    test_pattern:
      - spec/routing/root_route_spec.rb
  third:
    script: "/usr/local/repos/successful_test"
    test_pattern:
      - spec/features/tasks/editTaskText_spec.rb
  fourth:
    script: "/usr/local/repos/successful_test"
  fifth:
    script: "/usr/local/repos/successful_test"
  six:
    script: "/usr/local/repos/successful_test"
  seventh:
    script: "/usr/local/repos/successful_test"
  eight:
    script: "/usr/local/repos/successful_test"
  nine:
    script: "/usr/local/repos/successful_test"
  ten:
    script: "/usr/local/repos/successful_test"
  eleven:
    script: "/usr/local/repos/successful_test"
  twelve:
    script: "/usr/local/repos/successful_test"
  thirteen:
    script: "/usr/local/repos/successful_test"
  fourteen:
    script: "/usr/local/repos/successful_test"
  fifteen:
    script: "/usr/local/repos/successful_test"
