default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000
  username: rails_user
  password: 'password'

development:
  <<: *default
  database: task_manager

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_prod
