ruby_version: ruby-2.3.0-p0
bundler_version: "1.12.2"

test_pattern:
  - spec/controllers/*_spec.rb
  - spec/models/*_spec.rb

rake:
  rails_env: test

postgresql:
  version: '9.3'

firefox: '46.0'

hooks:
  package_setup: |
    set -e
    date > $HOME/package_install.txt
    printenv
    # rbenv install -l > debug.txt
    # rbenv versions > debug.txt
    # ruby -v > debug.txt
    rbenv global 2.3.0
    bundle install
    bin/rake db:migrate RAILS_ENV=test

collect:
  repo:
    - debug.txt
